name: PR Check

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - ${{ github.event.repository.default_branch }}
      - next

jobs:
  validate:
    uses: ./.github/workflows/ci.yml
